// <auto-generated />
using System;
using IoTServices.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IoTServices.Migrations
{
    [DbContext(typeof(IotDbContext))]
    partial class IotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("IoTServices.Data.IotData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Altitudine")
                        .HasColumnType("REAL");

                    b.Property<int>("IdDevice")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Pressione")
                        .HasColumnType("REAL");

                    b.Property<float>("Temperatura")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.Property<float>("Umidita")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("IotData");
                });
#pragma warning restore 612, 618
        }
    }
}
